python3 ../../lxbuildenv.py -r -m unittest -v valentyusb.usbcore.cpu.epfifo_test
test_control_setup (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_control_setup_clears_stall (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_control_transfer_in (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_control_transfer_in_nak_data (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_control_transfer_in_nak_status (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_control_transfer_out (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_control_transfer_out_nak_data (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_control_transfer_out_nak_status (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_data_in_byte_1 (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_data_in_byte_2 (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_data_in_byte_a (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_data_toggle_bit_multiple_endpoints (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_in_stall (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_in_transfer (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_in_transfer_nak (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_out_stall (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_out_transfer (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_out_transfer_nak (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_setup_clears_data_toggle_bit (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_sof_is_ignored (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok
test_sof_stuffing (valentyusb.usbcore.cpu.epfifo_test.TestPerEndpointFifoInterface) ... ok

----------------------------------------------------------------------
Ran 21 tests in 1009.411s

OK
./run_tests.sh: line 7: ep(0,: command not found
python3 ../../lxbuildenv.py -r -m unittest -v valentyusb.usbcore.cpu.epmem_test
test_control_setup (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... ok
test_control_setup_clears_stall (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... ok
test_control_transfer_in (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... FAIL
test_control_transfer_in_nak_data (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... ok
test_control_transfer_in_nak_status (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... ok
test_control_transfer_out (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... FAIL
test_control_transfer_out_nak_data (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... ok
test_control_transfer_out_nak_status (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... FAIL
test_data_in_byte_1 (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... ok
test_data_in_byte_2 (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... ok
test_data_in_byte_a (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... ok
test_data_toggle_bit_multiple_endpoints (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... FAIL
test_in_stall (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... FAIL
test_in_transfer (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... FAIL
test_in_transfer_nak (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... ok
test_out_stall (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... FAIL
test_out_transfer (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... FAIL
test_out_transfer_nak (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... ok
test_setup_clears_data_toggle_bit (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... FAIL
test_sof_is_ignored (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... ok
test_sof_stuffing (valentyusb.usbcore.cpu.epmem_test.TestMemInterface) ... ok

======================================================================
FAIL: test_control_transfer_in (valentyusb.usbcore.cpu.epmem_test.TestMemInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 631, in test_control_transfer_in
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/epmem_test.py", line 65, in run_sim
    "usb_12": 32,
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/epmem_test.py", line 53, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 629, in stim
    0x08, 0x09, 0x0A, 0x0B],
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 415, in control_transfer_in
    yield from self.transaction_data_in(addr, epaddr_in, descriptor_data)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 362, in transaction_data_in
    yield from self.check_no_pending_and_respond_ack(epaddr)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 272, in check_no_pending_and_respond_ack
    self.assertEqual((yield from self.response(epaddr)), EndpointResponse.ACK)
AssertionError: <EndpointResponse.NAK: 1> != <EndpointResponse.ACK: 0>

======================================================================
FAIL: test_control_transfer_out (valentyusb.usbcore.cpu.epmem_test.TestMemInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 714, in test_control_transfer_out
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/epmem_test.py", line 65, in run_sim
    "usb_12": 32,
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/epmem_test.py", line 53, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 712, in stim
    0x08, 0x09, 0x0A, 0x0B],
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 434, in control_transfer_out
    yield from self.transaction_data_out(addr, epaddr_out, descriptor_data)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 319, in transaction_data_out
    yield from self.expect_ack()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 248, in expect_ack
    yield from self.expect_packet(handshake_packet(PID.ACK), "Expected ACK packet.")
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 236, in expect_packet
    self.assertMultiLineEqualSideBySide(expected, actual, msg)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 118, in assertMultiLineEqualSideBySide
    return assertMultiLineEqualSideBySide(data1, data2, msg)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/utils/asserts.py", line 44, in assertMultiLineEqualSideBySide
    assert False, msg
AssertionError: Expected ACK packet.
      |expected                                                                                                                                 |actual
      |--------                                                                                                                                 |--------
     6|KKKK 5 Sync                                                                                                                             6|KKKK 5 Sync
     7|JJJJ 6 Sync                                                                                                                             7|JJJJ 6 Sync
     8|KKKK 7 Sync                                                                                                                             8|KKKK 7 Sync
     9|KKKK 8 Sync                                                                                                                             9|KKKK 8 Sync
    10|----                                                                                                                                   10|----
    11|JJJJ 1 PID (PID.ACK)                                                                                                             |     11|JJJJ 1 PID (PID.NAK)
    12|JJJJ 2 PID                                                                                                                             12|JJJJ 2 PID
    13|KKKK 3 PID                                                                                                                             13|KKKK 3 PID
    14|JJJJ 4 PID                                                                                                                       |     14|KKKK 4 PID
    15|JJJJ 5 PID                                                                                                                       |     15|KKKK 5 PID
    16|KKKK 6 PID                                                                                                                       |     16|JJJJ 6 PID
    17|KKKK 7 PID                                                                                                                       |     17|JJJJ 7 PID
    18|KKKK 8 PID                                                                                                                             18|KKKK 8 PID
    19|----                                                                                                                                   19|----
    20|____ SE0                                                                                                                               20|____ SE0
    21|____ SE0                                                                                                                               21|____ SE0
    22|JJJJ END                                                                                                                               22|JJJJ END

[     ]      |                + -   
[ <-  ]    11|JJJJ 1 PID (PID. ACK) 
[  -> ]    11|JJJJ 1 PID (PID.NA K) 

[     ]      |!!!!       
[ <-  ]    14|JJJJ 4 PID 
[  -> ]    14|KKKK 4 PID 

[     ]      |!!!!       
[ <-  ]    15|JJJJ 5 PID 
[  -> ]    15|KKKK 5 PID 

[     ]      |!!!!       
[ <-  ]    16|KKKK 6 PID 
[  -> ]    16|JJJJ 6 PID 

[     ]      |!!!!       
[ <-  ]    17|KKKK 7 PID 
[  -> ]    17|JJJJ 7 PID 


======================================================================
FAIL: test_control_transfer_out_nak_status (valentyusb.usbcore.cpu.epmem_test.TestMemInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 798, in test_control_transfer_out_nak_status
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/epmem_test.py", line 65, in run_sim
    "usb_12": 32,
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/epmem_test.py", line 53, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 778, in stim
    yield from self.transaction_data_in(addr, epaddr_in, descriptor_data)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 362, in transaction_data_in
    yield from self.check_no_pending_and_respond_ack(epaddr)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 272, in check_no_pending_and_respond_ack
    self.assertEqual((yield from self.response(epaddr)), EndpointResponse.ACK)
AssertionError: <EndpointResponse.NAK: 1> != <EndpointResponse.ACK: 0>

======================================================================
FAIL: test_data_toggle_bit_multiple_endpoints (valentyusb.usbcore.cpu.epmem_test.TestMemInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 998, in test_data_toggle_bit_multiple_endpoints
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/epmem_test.py", line 65, in run_sim
    "usb_12": 32,
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/epmem_test.py", line 53, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 986, in stim
    yield from self.expect_data_packet(PID.DATA0, d3)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 243, in expect_data_packet
    yield from self.expect_packet(data_packet(pid, data), "Expected %s packet with %r" % (pid.name, data))
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 236, in expect_packet
    self.assertMultiLineEqualSideBySide(expected, actual, msg)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 118, in assertMultiLineEqualSideBySide
    return assertMultiLineEqualSideBySide(data1, data2, msg)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/utils/asserts.py", line 44, in assertMultiLineEqualSideBySide
    assert False, msg
AssertionError: Expected DATA0 packet with [3]
      |expected                                                                                                                                 |actual
      |--------                                                                                                                                 |--------
     6|KKKK 5 Sync                                                                                                                             6|KKKK 5 Sync
     7|JJJJ 6 Sync                                                                                                                             7|JJJJ 6 Sync
     8|KKKK 7 Sync                                                                                                                             8|KKKK 7 Sync
     9|KKKK 8 Sync                                                                                                                             9|KKKK 8 Sync
    10|----                                                                                                                                   10|----
    11|KKKK 1 PID (PID.DATA0)                                                                                                           |     11|JJJJ 1 PID (PID.NAK)
    12|KKKK 2 PID                                                                                                                       |     12|JJJJ 2 PID
    13|JJJJ 3 PID                                                                                                                       |     13|KKKK 3 PID
    14|KKKK 4 PID                                                                                                                             14|KKKK 4 PID
    15|JJJJ 5 PID                                                                                                                       |     15|KKKK 5 PID
    16|KKKK 6 PID                                                                                                                       |     16|JJJJ 6 PID
    17|KKKK 7 PID                                                                                                                       |     17|JJJJ 7 PID
    18|KKKK 8 PID                                                                                                                             18|KKKK 8 PID
    19|----                                                                                                                             <       |
    20|KKKK                                                                                                                             <       |
    21|KKKK                                                                                                                             <       |
    22|JJJJ                                                                                                                             <       |
    23|KKKK                                                                                                                             <       |
    24|JJJJ                                                                                                                             <       |
    25|KKKK                                                                                                                             <       |
    26|JJJJ                                                                                                                             <       |
    27|KKKK                                                                                                                             <       |
    28|----                                                                                                                             <       |
    29|JJJJ  1 CRC16                                                                                                                    <       |
    30|KKKK  2 CRC16                                                                                                                    <       |
    31|JJJJ  3 CRC16                                                                                                                    <       |
    32|KKKK  4 CRC16                                                                                                                    <       |
    33|JJJJ  5 CRC16                                                                                                                    <       |
    34|KKKK  6 CRC16                                                                                                                    <       |
    35|JJJJ  7 CRC16                                                                                                                    <       |
    36|KKKK  8 CRC16                                                                                                                    <       |
    37|----                                                                                                                             <       |
    38|JJJJ  9 CRC16                                                                                                                    <       |
    39|JJJJ 10 CRC16                                                                                                                    <       |
    40|JJJJ 11 CRC16                                                                                                                    <       |
    41|JJJJ 12 CRC16                                                                                                                    <       |
    42|JJJJ 13 CRC16                                                                                                                    <       |
    43|JJJJ 14 CRC16                                                                                                                    <       |
    44|KKKK 15 CRC16                                                                                                                    <       |
    45|KKKK 16 CRC16                                                                                                                    <       |
    46|----                                                                                                                                   19|----
    47|____ SE0                                                                                                                               20|____ SE0
    48|____ SE0                                                                                                                               21|____ SE0
    49|JJJJ END                                                                                                                               22|JJJJ END

[     ]      |!!!!            ! !--  
[ <-  ]    11|KKKK 1 PID (PID.DATA0) 
[  -> ]    11|JJJJ 1 PID (PID.NAK  ) 

[     ]      |!!!!       
[ <-  ]    12|KKKK 2 PID 
[  -> ]    12|JJJJ 2 PID 

[     ]      |!!!!       
[ <-  ]    13|JJJJ 3 PID 
[  -> ]    13|KKKK 3 PID 

[     ]      |!!!!       
[ <-  ]    15|JJJJ 5 PID 
[  -> ]    15|KKKK 5 PID 

[     ]      |!!!!       
[ <-  ]    16|KKKK 6 PID 
[  -> ]    16|JJJJ 6 PID 

[     ]      |!!!!       
[ <-  ]    17|KKKK 7 PID 
[  -> ]    17|JJJJ 7 PID 


======================================================================
FAIL: test_in_stall (valentyusb.usbcore.cpu.epmem_test.TestMemInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 1078, in test_in_stall
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/epmem_test.py", line 65, in run_sim
    "usb_12": 32,
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/epmem_test.py", line 53, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 1057, in stim
    yield from self.expect_nak()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 253, in expect_nak
    yield from self.expect_packet(handshake_packet(PID.NAK), "Expected NAK packet.")
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 236, in expect_packet
    self.assertMultiLineEqualSideBySide(expected, actual, msg)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 118, in assertMultiLineEqualSideBySide
    return assertMultiLineEqualSideBySide(data1, data2, msg)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/utils/asserts.py", line 44, in assertMultiLineEqualSideBySide
    assert False, msg
AssertionError: Expected NAK packet.
      |expected                                                                                                                                 |actual
      |--------                                                                                                                                 |--------
     6|KKKK 5 Sync                                                                                                                             6|KKKK 5 Sync
     7|JJJJ 6 Sync                                                                                                                             7|JJJJ 6 Sync
     8|KKKK 7 Sync                                                                                                                             8|KKKK 7 Sync
     9|KKKK 8 Sync                                                                                                                             9|KKKK 8 Sync
    10|----                                                                                                                                   10|----
    11|JJJJ 1 PID (PID.NAK)                                                                                                             |     11|KKKK 1 PID (PID.DATA1)
    12|JJJJ 2 PID                                                                                                                       |     12|KKKK 2 PID
    13|KKKK 3 PID                                                                                                                       |     13|JJJJ 3 PID
    14|KKKK 4 PID                                                                                                                       |     14|JJJJ 4 PID
    15|KKKK 5 PID                                                                                                                             15|KKKK 5 PID
    16|JJJJ 6 PID                                                                                                                             16|JJJJ 6 PID
    17|JJJJ 7 PID                                                                                                                             17|JJJJ 7 PID
    18|KKKK 8 PID                                                                                                                             18|KKKK 8 PID
    19|----                                                                                                                                   19|----
      |                                                                                                                                 >     20|KKKK
      |                                                                                                                                 >     21|JJJJ
      |                                                                                                                                 >     22|KKKK
      |                                                                                                                                 >     23|JJJJ
      |                                                                                                                                 >     24|KKKK
      |                                                                                                                                 >     25|JJJJ
      |                                                                                                                                 >     26|KKKK
      |                                                                                                                                 >     27|JJJJ
      |                                                                                                                                 >     28|----
      |                                                                                                                                 >     29|KKKK
      |                                                                                                                                 >     30|KKKK
      |                                                                                                                                 >     31|JJJJ
      |                                                                                                                                 >     32|KKKK
      |                                                                                                                                 >     33|JJJJ
      |                                                                                                                                 >     34|KKKK
      |                                                                                                                                 >     35|JJJJ
      |                                                                                                                                 >     36|KKKK
      |                                                                                                                                 >     37|----
      |                                                                                                                                 >     38|KKKK
      |                                                                                                                                 >     39|KKKK
      |                                                                                                                                 >     40|JJJJ
      |                                                                                                                                 >     41|KKKK
      |                                                                                                                                 >     42|JJJJ
      |                                                                                                                                 >     43|KKKK
      |                                                                                                                                 >     44|JJJJ
      |                                                                                                                                 >     45|KKKK
      |                                                                                                                                 >     46|----
      |                                                                                                                                 >     47|JJJJ
      |                                                                                                                                 >     48|KKKK
      |                                                                                                                                 >     49|KKKK
      |                                                                                                                                 >     50|JJJJ
      |                                                                                                                                 >     51|KKKK
      |                                                                                                                                 >     52|JJJJ
      |                                                                                                                                 >     53|KKKK
      |                                                                                                                                 >     54|JJJJ
      |                                                                                                                                 >     55|----
      |                                                                                                                                 >     56|KKKK  1 CRC16
      |                                                                                                                                 >     57|KKKK  2 CRC16
      |                                                                                                                                 >     58|KKKK  3 CRC16
      |                                                                                                                                 >     59|KKKK  4 CRC16
      |                                                                                                                                 >     60|KKKK  5 CRC16
      |                                                                                                                                 >     61|JJJJ  6 CRC16
      |                                                                                                                                 >     62|JJJJ  7 CRC16
      |                                                                                                                                 >     63|KKKK  8 CRC16
      |                                                                                                                                 >     64|----
      |                                                                                                                                 >     65|JJJJ  9 CRC16
      |                                                                                                                                 >     66|KKKK 10 CRC16
      |                                                                                                                                 >     67|KKKK 11 CRC16
      |                                                                                                                                 >     68|JJJJ 12 CRC16
      |                                                                                                                                 >     69|JJJJ 13 CRC16
      |                                                                                                                                 >     70|KKKK 14 CRC16
      |                                                                                                                                 >     71|KKKK 15 CRC16
      |                                                                                                                                 >     72|KKKK 16 CRC16
      |                                                                                                                                 >     73|----
    20|____ SE0                                                                                                                               74|____ SE0
    21|____ SE0                                                                                                                               75|____ SE0
    22|JJJJ END                                                                                                                               76|JJJJ END

[     ]      |!!!!            ! !++  
[ <-  ]    11|JJJJ 1 PID (PID.NAK  ) 
[  -> ]    11|KKKK 1 PID (PID.DATA1) 

[     ]      |!!!!       
[ <-  ]    12|JJJJ 2 PID 
[  -> ]    12|KKKK 2 PID 

[     ]      |!!!!       
[ <-  ]    13|KKKK 3 PID 
[  -> ]    13|JJJJ 3 PID 

[     ]      |!!!!       
[ <-  ]    14|KKKK 4 PID 
[  -> ]    14|JJJJ 4 PID 


======================================================================
FAIL: test_in_transfer (valentyusb.usbcore.cpu.epmem_test.TestMemInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 825, in test_in_transfer
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/epmem_test.py", line 65, in run_sim
    "usb_12": 32,
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/epmem_test.py", line 53, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 822, in stim
    yield from self.expect_data_packet(PID.DATA0, d[4:])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 243, in expect_data_packet
    yield from self.expect_packet(data_packet(pid, data), "Expected %s packet with %r" % (pid.name, data))
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 236, in expect_packet
    self.assertMultiLineEqualSideBySide(expected, actual, msg)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 118, in assertMultiLineEqualSideBySide
    return assertMultiLineEqualSideBySide(data1, data2, msg)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/utils/asserts.py", line 44, in assertMultiLineEqualSideBySide
    assert False, msg
AssertionError: Expected DATA0 packet with [5, 6, 7, 8]
      |expected                                                                                                                                 |actual
      |--------                                                                                                                                 |--------
     6|KKKK 5 Sync                                                                                                                             6|KKKK 5 Sync
     7|JJJJ 6 Sync                                                                                                                             7|JJJJ 6 Sync
     8|KKKK 7 Sync                                                                                                                             8|KKKK 7 Sync
     9|KKKK 8 Sync                                                                                                                             9|KKKK 8 Sync
    10|----                                                                                                                                   10|----
    11|KKKK 1 PID (PID.DATA0)                                                                                                           |     11|JJJJ 1 PID (PID.NAK)
    12|KKKK 2 PID                                                                                                                       |     12|JJJJ 2 PID
    13|JJJJ 3 PID                                                                                                                       |     13|KKKK 3 PID
    14|KKKK 4 PID                                                                                                                             14|KKKK 4 PID
    15|JJJJ 5 PID                                                                                                                       |     15|KKKK 5 PID
    16|KKKK 6 PID                                                                                                                       |     16|JJJJ 6 PID
    17|KKKK 7 PID                                                                                                                       |     17|JJJJ 7 PID
    18|KKKK 8 PID                                                                                                                             18|KKKK 8 PID
    19|----                                                                                                                             <       |
    20|KKKK                                                                                                                             <       |
    21|JJJJ                                                                                                                             <       |
    22|JJJJ                                                                                                                             <       |
    23|KKKK                                                                                                                             <       |
    24|JJJJ                                                                                                                             <       |
    25|KKKK                                                                                                                             <       |
    26|JJJJ                                                                                                                             <       |
    27|KKKK                                                                                                                             <       |
    28|----                                                                                                                             <       |
    29|JJJJ                                                                                                                             <       |
    30|JJJJ                                                                                                                             <       |
    31|JJJJ                                                                                                                             <       |
    32|KKKK                                                                                                                             <       |
    33|JJJJ                                                                                                                             <       |
    34|KKKK                                                                                                                             <       |
    35|JJJJ                                                                                                                             <       |
    36|KKKK                                                                                                                             <       |
    37|----                                                                                                                             <       |
    38|KKKK                                                                                                                             <       |
    39|KKKK                                                                                                                             <       |
    40|KKKK                                                                                                                             <       |
    41|JJJJ                                                                                                                             <       |
    42|KKKK                                                                                                                             <       |
    43|JJJJ                                                                                                                             <       |
    44|KKKK                                                                                                                             <       |
    45|JJJJ                                                                                                                             <       |
    46|----                                                                                                                             <       |
    47|KKKK                                                                                                                             <       |
    48|JJJJ                                                                                                                             <       |
    49|KKKK                                                                                                                             <       |
    50|KKKK                                                                                                                             <       |
    51|JJJJ                                                                                                                             <       |
    52|KKKK                                                                                                                             <       |
    53|JJJJ                                                                                                                             <       |
    54|KKKK                                                                                                                             <       |
    55|----                                                                                                                             <       |
    56|JJJJ  1 CRC16                                                                                                                    <       |
    57|KKKK  2 CRC16                                                                                                                    <       |
    58|KKKK  3 CRC16                                                                                                                    <       |
    59|KKKK  4 CRC16                                                                                                                    <       |
    60|KKKK  5 CRC16                                                                                                                    <       |
    61|JJJJ  6 CRC16                                                                                                                    <       |
    62|KKKK  7 CRC16                                                                                                                    <       |
    63|JJJJ  8 CRC16                                                                                                                    <       |
    64|----                                                                                                                             <       |
    65|KKKK  9 CRC16                                                                                                                    <       |
    66|JJJJ 10 CRC16                                                                                                                    <       |
    67|KKKK 11 CRC16                                                                                                                    <       |
    68|JJJJ 12 CRC16                                                                                                                    <       |
    69|KKKK 13 CRC16                                                                                                                    <       |
    70|KKKK 14 CRC16                                                                                                                    <       |
    71|KKKK 15 CRC16                                                                                                                    <       |
    72|KKKK 16 CRC16                                                                                                                    <       |
    73|----                                                                                                                                   19|----
    74|____ SE0                                                                                                                               20|____ SE0
    75|____ SE0                                                                                                                               21|____ SE0
    76|JJJJ END                                                                                                                               22|JJJJ END

[     ]      |!!!!            ! !--  
[ <-  ]    11|KKKK 1 PID (PID.DATA0) 
[  -> ]    11|JJJJ 1 PID (PID.NAK  ) 

[     ]      |!!!!       
[ <-  ]    12|KKKK 2 PID 
[  -> ]    12|JJJJ 2 PID 

[     ]      |!!!!       
[ <-  ]    13|JJJJ 3 PID 
[  -> ]    13|KKKK 3 PID 

[     ]      |!!!!       
[ <-  ]    15|JJJJ 5 PID 
[  -> ]    15|KKKK 5 PID 

[     ]      |!!!!       
[ <-  ]    16|KKKK 6 PID 
[  -> ]    16|JJJJ 6 PID 

[     ]      |!!!!       
[ <-  ]    17|KKKK 7 PID 
[  -> ]    17|JJJJ 7 PID 


======================================================================
FAIL: test_out_stall (valentyusb.usbcore.cpu.epmem_test.TestMemInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 1195, in test_out_stall
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/epmem_test.py", line 65, in run_sim
    "usb_12": 32,
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/epmem_test.py", line 53, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 1171, in stim
    yield from self.expect_nak()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 253, in expect_nak
    yield from self.expect_packet(handshake_packet(PID.NAK), "Expected NAK packet.")
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 236, in expect_packet
    self.assertMultiLineEqualSideBySide(expected, actual, msg)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 118, in assertMultiLineEqualSideBySide
    return assertMultiLineEqualSideBySide(data1, data2, msg)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/utils/asserts.py", line 44, in assertMultiLineEqualSideBySide
    assert False, msg
AssertionError: Expected NAK packet.
      |expected                                                                                                                                 |actual
      |--------                                                                                                                                 |--------
     6|KKKK 5 Sync                                                                                                                             6|KKKK 5 Sync
     7|JJJJ 6 Sync                                                                                                                             7|JJJJ 6 Sync
     8|KKKK 7 Sync                                                                                                                             8|KKKK 7 Sync
     9|KKKK 8 Sync                                                                                                                             9|KKKK 8 Sync
    10|----                                                                                                                                   10|----
    11|JJJJ 1 PID (PID.NAK)                                                                                                             |     11|JJJJ 1 PID (PID.ACK)
    12|JJJJ 2 PID                                                                                                                             12|JJJJ 2 PID
    13|KKKK 3 PID                                                                                                                             13|KKKK 3 PID
    14|KKKK 4 PID                                                                                                                       |     14|JJJJ 4 PID
    15|KKKK 5 PID                                                                                                                       |     15|JJJJ 5 PID
    16|JJJJ 6 PID                                                                                                                       |     16|KKKK 6 PID
    17|JJJJ 7 PID                                                                                                                       |     17|KKKK 7 PID
    18|KKKK 8 PID                                                                                                                             18|KKKK 8 PID
    19|----                                                                                                                                   19|----
    20|____ SE0                                                                                                                               20|____ SE0
    21|____ SE0                                                                                                                               21|____ SE0
    22|JJJJ END                                                                                                                               22|JJJJ END

[     ]      |                - +   
[ <-  ]    11|JJJJ 1 PID (PID.NA K) 
[  -> ]    11|JJJJ 1 PID (PID. ACK) 

[     ]      |!!!!       
[ <-  ]    14|KKKK 4 PID 
[  -> ]    14|JJJJ 4 PID 

[     ]      |!!!!       
[ <-  ]    15|KKKK 5 PID 
[  -> ]    15|JJJJ 5 PID 

[     ]      |!!!!       
[ <-  ]    16|JJJJ 6 PID 
[  -> ]    16|KKKK 6 PID 

[     ]      |!!!!       
[ <-  ]    17|JJJJ 7 PID 
[  -> ]    17|KKKK 7 PID 


======================================================================
FAIL: test_out_transfer (valentyusb.usbcore.cpu.epmem_test.TestMemInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 1117, in test_out_transfer
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/epmem_test.py", line 65, in run_sim
    "usb_12": 32,
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/epmem_test.py", line 53, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 1113, in stim
    yield from self.expect_ack()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 248, in expect_ack
    yield from self.expect_packet(handshake_packet(PID.ACK), "Expected ACK packet.")
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 236, in expect_packet
    self.assertMultiLineEqualSideBySide(expected, actual, msg)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 118, in assertMultiLineEqualSideBySide
    return assertMultiLineEqualSideBySide(data1, data2, msg)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/utils/asserts.py", line 44, in assertMultiLineEqualSideBySide
    assert False, msg
AssertionError: Expected ACK packet.
      |expected                                                                                                                                 |actual
      |--------                                                                                                                                 |--------
     6|KKKK 5 Sync                                                                                                                             6|KKKK 5 Sync
     7|JJJJ 6 Sync                                                                                                                             7|JJJJ 6 Sync
     8|KKKK 7 Sync                                                                                                                             8|KKKK 7 Sync
     9|KKKK 8 Sync                                                                                                                             9|KKKK 8 Sync
    10|----                                                                                                                                   10|----
    11|JJJJ 1 PID (PID.ACK)                                                                                                             |     11|JJJJ 1 PID (PID.NAK)
    12|JJJJ 2 PID                                                                                                                             12|JJJJ 2 PID
    13|KKKK 3 PID                                                                                                                             13|KKKK 3 PID
    14|JJJJ 4 PID                                                                                                                       |     14|KKKK 4 PID
    15|JJJJ 5 PID                                                                                                                       |     15|KKKK 5 PID
    16|KKKK 6 PID                                                                                                                       |     16|JJJJ 6 PID
    17|KKKK 7 PID                                                                                                                       |     17|JJJJ 7 PID
    18|KKKK 8 PID                                                                                                                             18|KKKK 8 PID
    19|----                                                                                                                                   19|----
    20|____ SE0                                                                                                                               20|____ SE0
    21|____ SE0                                                                                                                               21|____ SE0
    22|JJJJ END                                                                                                                               22|JJJJ END

[     ]      |                + -   
[ <-  ]    11|JJJJ 1 PID (PID. ACK) 
[  -> ]    11|JJJJ 1 PID (PID.NA K) 

[     ]      |!!!!       
[ <-  ]    14|JJJJ 4 PID 
[  -> ]    14|KKKK 4 PID 

[     ]      |!!!!       
[ <-  ]    15|JJJJ 5 PID 
[  -> ]    15|KKKK 5 PID 

[     ]      |!!!!       
[ <-  ]    16|KKKK 6 PID 
[  -> ]    16|JJJJ 6 PID 

[     ]      |!!!!       
[ <-  ]    17|KKKK 7 PID 
[  -> ]    17|JJJJ 7 PID 


======================================================================
FAIL: test_setup_clears_data_toggle_bit (valentyusb.usbcore.cpu.epmem_test.TestMemInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 952, in test_setup_clears_data_toggle_bit
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/epmem_test.py", line 65, in run_sim
    "usb_12": 32,
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/epmem_test.py", line 53, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 898, in stim
    self.assertTrue(dtbi)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 21 tests in 496.723s

FAILED (failures=9)
python3 ../../lxbuildenv.py -r -m unittest -v valentyusb.usbcore.cpu.unififo_test
test_control_setup (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... ok
test_control_setup_clears_stall (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... ok
test_control_transfer_in (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... ok
test_control_transfer_in_nak_data (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... ok
test_control_transfer_in_nak_status (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... ok
test_control_transfer_out (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... ok
test_control_transfer_out_nak_data (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... ok
test_control_transfer_out_nak_status (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... ok
test_data_in_byte_1 (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... ok
test_data_in_byte_2 (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... ok
test_data_in_byte_a (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... ok
test_data_toggle_bit_multiple_endpoints (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... ok
test_in_stall (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... ok
test_in_transfer (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... ok
test_in_transfer_nak (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... ok
test_out_stall (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... ok
test_out_transfer (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... ok
test_out_transfer_nak (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... ok
test_setup_clears_data_toggle_bit (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... ok
test_sof_is_ignored (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... FAIL
test_sof_stuffing (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo) ... FAIL

======================================================================
FAIL: test_sof_is_ignored (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 571, in test_sof_is_ignored
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/unififo_test.py", line 113, in run_sim
    clocks=clocks,
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/unififo_test.py", line 99, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 504, in stim
    yield from self.tick_usb12()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/unififo_test.py", line 182, in tick_usb12
    yield from self.tick_usb48()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/unififo_test.py", line 178, in tick_usb48
    yield from self.wait_for_edge("usb_48")
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/clock.py", line 28, in wait_for_edge
    yield from self.update_internal_signals()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/unififo_test.py", line 258, in update_internal_signals
    assert False, pid
AssertionError: PID.SOF

======================================================================
FAIL: test_sof_stuffing (valentyusb.usbcore.cpu.unififo_test.TestUsbUniFifo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 484, in test_sof_stuffing
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/unififo_test.py", line 113, in run_sim
    clocks=clocks,
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/unififo_test.py", line 99, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 462, in stim
    yield from self.tick_usb12()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/unififo_test.py", line 182, in tick_usb12
    yield from self.tick_usb48()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/unififo_test.py", line 178, in tick_usb48
    yield from self.wait_for_edge("usb_48")
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/clock.py", line 28, in wait_for_edge
    yield from self.update_internal_signals()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/cpu/unififo_test.py", line 258, in update_internal_signals
    assert False, pid
AssertionError: PID.SOF

----------------------------------------------------------------------
Ran 21 tests in 780.759s

FAILED (failures=2)
./run_tests.sh: line 7: ----------: command not found
python3 ../../lxbuildenv.py -r -m unittest -v valentyusb.usbcore.io_test
test_recv_idle (valentyusb.usbcore.io_test.TestFakeIoBuf) ... ok
test_recv_j (valentyusb.usbcore.io_test.TestFakeIoBuf) ... ok
test_recv_k (valentyusb.usbcore.io_test.TestFakeIoBuf) ... ok
test_recv_se0 (valentyusb.usbcore.io_test.TestFakeIoBuf) ... ok
test_recv_se0_alias (valentyusb.usbcore.io_test.TestFakeIoBuf) ... ok

----------------------------------------------------------------------
Ran 5 tests in 0.012s

OK
python3 ../../lxbuildenv.py -r -m unittest -v valentyusb.usbcore.rx.bitstuff_test
test_bit_stuff (valentyusb.usbcore.rx.bitstuff_test.TestRxBitstuffRemover) ... ok
test_bit_stuff_after_reset (valentyusb.usbcore.rx.bitstuff_test.TestRxBitstuffRemover) ... ok
test_bit_stuff_error (valentyusb.usbcore.rx.bitstuff_test.TestRxBitstuffRemover) ... ok
test_bit_stuff_error_after_reset (valentyusb.usbcore.rx.bitstuff_test.TestRxBitstuffRemover) ... ok
test_captured_setup_packet_no_stuff (valentyusb.usbcore.rx.bitstuff_test.TestRxBitstuffRemover) ... ok
test_idle_packet_idle (valentyusb.usbcore.rx.bitstuff_test.TestRxBitstuffRemover) ... ok
test_idle_packet_idle_packet_idle (valentyusb.usbcore.rx.bitstuff_test.TestRxBitstuffRemover) ... ok
test_mixed_bit_stuff_error (valentyusb.usbcore.rx.bitstuff_test.TestRxBitstuffRemover) ... ok
test_multiple_bit_stuff_scenario (valentyusb.usbcore.rx.bitstuff_test.TestRxBitstuffRemover) ... ok
test_no_bit_stuff (valentyusb.usbcore.rx.bitstuff_test.TestRxBitstuffRemover) ... ok
test_valid_captured_setup_packet_no_stuff (valentyusb.usbcore.rx.bitstuff_test.TestRxBitstuffRemover) ... ok
test_valid_idle_packet_idle_packet_idle (valentyusb.usbcore.rx.bitstuff_test.TestRxBitstuffRemover) ... ok

----------------------------------------------------------------------
Ran 12 tests in 0.116s

OK
python3 ../../lxbuildenv.py -r -m unittest -v valentyusb.usbcore.rx.clock_test
test_0 (valentyusb.usbcore.rx.clock_test.TestRxClockDataRecovery) ... test_1 (valentyusb.usbcore.rx.clock_test.TestRxClockDataRecovery) ... ok
test_j (valentyusb.usbcore.rx.clock_test.TestRxClockDataRecovery) ... ok
test_jjjkj0j1kjkkk0k10j0k00011j1k1011 (valentyusb.usbcore.rx.clock_test.TestRxClockDataRecovery) ... ok
test_jk01 (valentyusb.usbcore.rx.clock_test.TestRxClockDataRecovery) ... ok
test_k (valentyusb.usbcore.rx.clock_test.TestRxClockDataRecovery) ... ok
test_kkkkk0k0kjjjk0kkkkjjjkjkjkjjj0kj (valentyusb.usbcore.rx.clock_test.TestRxClockDataRecovery) ... ok

======================================================================
FAIL: test_0 (valentyusb.usbcore.rx.clock_test.TestRxClockDataRecovery) (seq='0')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/rx/clock_test.py", line 90, in basic_recovery_test
    testsuffix="clock.basic_recovery_%s" % seq),
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/rx/clock_test.py", line 76, in stim
    self.assertEqual(out_seq, seq)
AssertionError: '00' != '0'
- 00
? -
+ 0


----------------------------------------------------------------------
Ran 7 tests in 0.098s

FAILED (failures=1)
python3 ../../lxbuildenv.py -r -m unittest -v valentyusb.usbcore.rx.crc_test
test_usb2_data_with_bad_crc16 (valentyusb.usbcore.rx.crc_test.TestRxCrcChecker) ... ok
test_usb2_data_with_good_crc16 (valentyusb.usbcore.rx.crc_test.TestRxCrcChecker) ... ok
test_usb2_token_with_bad_crc5 (valentyusb.usbcore.rx.crc_test.TestRxCrcChecker) ... ok
test_usb2_token_with_bad_crc5_2 (valentyusb.usbcore.rx.crc_test.TestRxCrcChecker) ... ok
test_usb2_token_with_good_crc5 (valentyusb.usbcore.rx.crc_test.TestRxCrcChecker) ... ok
test_usb2_token_with_good_crc5_1_2 (valentyusb.usbcore.rx.crc_test.TestRxCrcChecker) ... ok
test_usb2_token_with_good_crc5_2 (valentyusb.usbcore.rx.crc_test.TestRxCrcChecker) ... ok
test_usb2_token_with_good_crc5_and_pipeline_stalls (valentyusb.usbcore.rx.crc_test.TestRxCrcChecker) ... ok

----------------------------------------------------------------------
Ran 8 tests in 0.113s

OK
python3 ../../lxbuildenv.py -r -m unittest -v valentyusb.usbcore.rx.detect_test
test_idle_glitch (valentyusb.usbcore.rx.detect_test.TestRxPacketDetect) ... ok
test_idle_packet_idle (valentyusb.usbcore.rx.detect_test.TestRxPacketDetect) ... ok
test_idle_packet_idle_packet_idle (valentyusb.usbcore.rx.detect_test.TestRxPacketDetect) ... ok
test_idle_packet_idle_stall (valentyusb.usbcore.rx.detect_test.TestRxPacketDetect) ... ok
test_idle_packet_idle_stalls (valentyusb.usbcore.rx.detect_test.TestRxPacketDetect) ... ok
test_idle_sync_idle (valentyusb.usbcore.rx.detect_test.TestRxPacketDetect) ... ok
test_se0_idle (valentyusb.usbcore.rx.detect_test.TestRxPacketDetect) ... ok
test_valid_idle_packet_idle_packet_idle (valentyusb.usbcore.rx.detect_test.TestRxPacketDetect) ... ok

----------------------------------------------------------------------
Ran 8 tests in 0.079s

OK
python3 ../../lxbuildenv.py -r -m unittest -v valentyusb.usbcore.rx.nrzi_test
test_captured_setup_packet (valentyusb.usbcore.rx.nrzi_test.TestRxNRZIDecoder) ... ok
test_captured_setup_packet_stalls (valentyusb.usbcore.rx.nrzi_test.TestRxNRZIDecoder) ... ok
test_usb2_spec_7_1_8 (valentyusb.usbcore.rx.nrzi_test.TestRxNRZIDecoder) ... ok
test_usb2_spec_7_1_9_1 (valentyusb.usbcore.rx.nrzi_test.TestRxNRZIDecoder) ... ok
test_usb2_spec_7_1_9_1_stalls (valentyusb.usbcore.rx.nrzi_test.TestRxNRZIDecoder) ... ok
test_usb2_spec_7_1_9_1_stalls_2 (valentyusb.usbcore.rx.nrzi_test.TestRxNRZIDecoder) ... ok
test_usb2_spec_7_1_9_1_stalls_3 (valentyusb.usbcore.rx.nrzi_test.TestRxNRZIDecoder) ... ok
test_usb2_spec_7_1_9_1_stalls_se0_glitch (valentyusb.usbcore.rx.nrzi_test.TestRxNRZIDecoder) ... ok

----------------------------------------------------------------------
Ran 8 tests in 0.052s

OK
python3 ../../lxbuildenv.py -r -m unittest -v valentyusb.usbcore.rx.pipeline_test
test_usb2_ack_handshake (valentyusb.usbcore.rx.pipeline_test.TestRxPipeline) ... ok
test_usb2_ack_handshake_eop_dribble_1 (valentyusb.usbcore.rx.pipeline_test.TestRxPipeline) ... ok
test_usb2_ack_handshake_eop_dribble_6 (valentyusb.usbcore.rx.pipeline_test.TestRxPipeline) ... ok
test_usb2_ack_handshake_pid_error (valentyusb.usbcore.rx.pipeline_test.TestRxPipeline) ... ok
test_usb2_data_with_bad_crc16 (valentyusb.usbcore.rx.pipeline_test.TestRxPipeline) ... ok
test_usb2_data_with_good_crc16 (valentyusb.usbcore.rx.pipeline_test.TestRxPipeline) ... ok
test_usb2_data_with_good_crc16_1_eop_dribble (valentyusb.usbcore.rx.pipeline_test.TestRxPipeline) ... ok
test_usb2_data_with_good_crc16_6_eop_dribble (valentyusb.usbcore.rx.pipeline_test.TestRxPipeline) ... ok
test_usb2_sof_stuffed_end (valentyusb.usbcore.rx.pipeline_test.TestRxPipeline) ... ok
test_usb2_sof_stuffed_mid (valentyusb.usbcore.rx.pipeline_test.TestRxPipeline) ... ok
test_usb2_sof_token (valentyusb.usbcore.rx.pipeline_test.TestRxPipeline) ... ok
test_usb2_sof_token_1 (valentyusb.usbcore.rx.pipeline_test.TestRxPipeline) ... ok
test_usb2_sof_token_bad_crc5 (valentyusb.usbcore.rx.pipeline_test.TestRxPipeline) ... ok
test_usb2_sof_token_bad_pid (valentyusb.usbcore.rx.pipeline_test.TestRxPipeline) ... ok
test_usb2_sof_token_eop_dribble_1 (valentyusb.usbcore.rx.pipeline_test.TestRxPipeline) ... ok
test_usb2_sof_token_eop_dribble_6 (valentyusb.usbcore.rx.pipeline_test.TestRxPipeline) ... ok

----------------------------------------------------------------------
Ran 16 tests in 21.485s

OK
python3 ../../lxbuildenv.py -r -m unittest -v valentyusb.usbcore.rx.shifter_test
test_basic_shift_in (valentyusb.usbcore.rx.shifter_test.TestRxShifter) ... ok
test_basic_shift_in_1 (valentyusb.usbcore.rx.shifter_test.TestRxShifter) ... ok
test_basic_shift_in_2 (valentyusb.usbcore.rx.shifter_test.TestRxShifter) ... ok
test_basic_shift_in_2_bytes (valentyusb.usbcore.rx.shifter_test.TestRxShifter) ... ok
test_basic_shift_in_3 (valentyusb.usbcore.rx.shifter_test.TestRxShifter) ... ok
test_basic_shift_in_4 (valentyusb.usbcore.rx.shifter_test.TestRxShifter) ... ok
test_basic_shift_in_5 (valentyusb.usbcore.rx.shifter_test.TestRxShifter) ... ok
test_basic_shift_in_6 (valentyusb.usbcore.rx.shifter_test.TestRxShifter) ... ok
test_basic_shift_in_7 (valentyusb.usbcore.rx.shifter_test.TestRxShifter) ... ok
test_multiple_resets (valentyusb.usbcore.rx.shifter_test.TestRxShifter) ... ok
test_multiple_resets_tight_timing (valentyusb.usbcore.rx.shifter_test.TestRxShifter) ... ok

----------------------------------------------------------------------
Ran 11 tests in 0.069s

OK
python3 ../../lxbuildenv.py -r -m unittest -v valentyusb.usbcore.sm.header_test
test_decode_ack (valentyusb.usbcore.sm.header_test.TestPacketHeaderDecode) ... FAIL
test_decode_data0 (valentyusb.usbcore.sm.header_test.TestPacketHeaderDecode) ... FAIL
test_decode_data1 (valentyusb.usbcore.sm.header_test.TestPacketHeaderDecode) ... FAIL
test_decode_in_ep1 (valentyusb.usbcore.sm.header_test.TestPacketHeaderDecode) ... FAIL
test_decode_nak (valentyusb.usbcore.sm.header_test.TestPacketHeaderDecode) ... FAIL
test_decode_out_ep8 (valentyusb.usbcore.sm.header_test.TestPacketHeaderDecode) ... FAIL
test_decode_setup_zero (valentyusb.usbcore.sm.header_test.TestPacketHeaderDecode) ... FAIL

======================================================================
FAIL: test_decode_ack (valentyusb.usbcore.sm.header_test.TestPacketHeaderDecode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 135, in test_decode_ack
    self.check_handshake(PID.ACK)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 116, in check_handshake
    wrap_packet(handshake_packet(expected_pid)),
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 92, in check_packet
    self.sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 25, in sim
    clocks={"sys": 12, "usb_48": 48, "usb_12": 192},
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 82, in stim
    self.assertTrue(decoded)
AssertionError: 0 is not true

======================================================================
FAIL: test_decode_data0 (valentyusb.usbcore.sm.header_test.TestPacketHeaderDecode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 129, in test_decode_data0
    self.check_status(PID.DATA0)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 110, in check_status
    wrap_packet(data_packet(expected_pid, [])),
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 92, in check_packet
    self.sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 25, in sim
    clocks={"sys": 12, "usb_48": 48, "usb_12": 192},
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 75, in stim
    tick,
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 61, in recv_packet
    self.assertFalse(continue_sim)
AssertionError: True is not false

======================================================================
FAIL: test_decode_data1 (valentyusb.usbcore.sm.header_test.TestPacketHeaderDecode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 132, in test_decode_data1
    self.check_status(PID.DATA1)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 110, in check_status
    wrap_packet(data_packet(expected_pid, [])),
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 92, in check_packet
    self.sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 25, in sim
    clocks={"sys": 12, "usb_48": 48, "usb_12": 192},
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 75, in stim
    tick,
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 61, in recv_packet
    self.assertFalse(continue_sim)
AssertionError: True is not false

======================================================================
FAIL: test_decode_in_ep1 (valentyusb.usbcore.sm.header_test.TestPacketHeaderDecode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 123, in test_decode_in_ep1
    self.check_token(PID.IN, 28, 1)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 97, in check_token
    wrap_packet(token_packet(expected_pid, expected_addr, expected_endp)),
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 92, in check_packet
    self.sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 25, in sim
    clocks={"sys": 12, "usb_48": 48, "usb_12": 192},
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 82, in stim
    self.assertTrue(decoded)
AssertionError: 0 is not true

======================================================================
FAIL: test_decode_nak (valentyusb.usbcore.sm.header_test.TestPacketHeaderDecode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 138, in test_decode_nak
    self.check_handshake(PID.NAK)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 116, in check_handshake
    wrap_packet(handshake_packet(expected_pid)),
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 92, in check_packet
    self.sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 25, in sim
    clocks={"sys": 12, "usb_48": 48, "usb_12": 192},
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 82, in stim
    self.assertTrue(decoded)
AssertionError: 0 is not true

======================================================================
FAIL: test_decode_out_ep8 (valentyusb.usbcore.sm.header_test.TestPacketHeaderDecode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 126, in test_decode_out_ep8
    self.check_token(PID.OUT, 12, 0xf)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 97, in check_token
    wrap_packet(token_packet(expected_pid, expected_addr, expected_endp)),
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 92, in check_packet
    self.sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 25, in sim
    clocks={"sys": 12, "usb_48": 48, "usb_12": 192},
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 82, in stim
    self.assertTrue(decoded)
AssertionError: 0 is not true

======================================================================
FAIL: test_decode_setup_zero (valentyusb.usbcore.sm.header_test.TestPacketHeaderDecode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 120, in test_decode_setup_zero
    self.check_token(PID.SETUP, 0x0, 0x0)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 97, in check_token
    wrap_packet(token_packet(expected_pid, expected_addr, expected_endp)),
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 92, in check_packet
    self.sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 25, in sim
    clocks={"sys": 12, "usb_48": 48, "usb_12": 192},
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/header_test.py", line 82, in stim
    self.assertTrue(decoded)
AssertionError: 0 is not true

----------------------------------------------------------------------
Ran 7 tests in 23.311s

FAILED (failures=7)
python3 ../../lxbuildenv.py -r -m unittest -v valentyusb.usbcore.sm.send_test
test_ack (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc) ... ERROR
test_data0_all_zero (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc) ... ERROR
test_data0_dat1234 (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc) ... ERROR
test_data0_descriptor (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc) ... ERROR
test_data0_edges (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc) ... ERROR
test_data0_one_one (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc) ... ERROR
test_data0_one_zero (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc) ... ERROR
test_data0_two_ones (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc) ... ERROR
test_data1_all_zero (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc) ... ERROR
test_nak (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc) ... ERROR
test_stall (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc) ... ERROR
test_status0 (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc) ... ERROR
test_status1 (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc) ... ERROR
test_ack (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc) ... ERROR
test_data0_all_zero (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc) ... ERROR
test_data0_dat1234 (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc) ... ERROR
test_data0_descriptor (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc) ... ERROR
test_data0_edges (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc) ... ERROR
test_data0_one_one (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc) ... ERROR
test_data0_one_zero (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc) ... ERROR
test_data0_two_ones (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc) ... ERROR
test_data1_all_zero (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc) ... ERROR
test_nak (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc) ... ERROR
test_stall (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc) ... ERROR
test_status0 (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc) ... ERROR
test_status1 (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc) ... ERROR

======================================================================
ERROR: test_ack (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 121, in test_ack
    self.sim(PID.ACK)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 207, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendAutoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_data0_all_zero (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 154, in test_data0_all_zero
    self.sim(PID.DATA0, data=[0, 0, 0, 0])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 207, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendAutoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_data0_dat1234 (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 157, in test_data0_dat1234
    self.sim(PID.DATA0, data=[1, 2, 3, 4])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 207, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendAutoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_data0_descriptor (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 164, in test_data0_descriptor
    0x80, 0x06, 0x00, 0x01, 0x00, 0x00, 0x40, 0x00, 0xdd, 0x94,
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 207, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendAutoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_data0_edges (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 151, in test_data0_edges
    self.sim(PID.DATA0, data=[0b00000001, 0, 0, 0b10000000])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 207, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendAutoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_data0_one_one (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 142, in test_data0_one_one
    self.sim(PID.DATA0, [0b10000001])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 207, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendAutoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_data0_one_zero (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 136, in test_data0_one_zero
    self.sim(PID.DATA0, [0])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 207, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendAutoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_data0_two_ones (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 148, in test_data0_two_ones
    self.sim(PID.DATA0, [0, 1])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 207, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendAutoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_data1_all_zero (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 160, in test_data1_all_zero
    self.sim(PID.DATA1, data=[0, 0, 0, 0])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 207, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendAutoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_nak (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 124, in test_nak
    self.sim(PID.NAK)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 207, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendAutoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_stall (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 127, in test_stall
    self.sim(PID.STALL)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 207, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendAutoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_status0 (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 130, in test_status0
    self.sim(PID.DATA0, [])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 207, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendAutoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_status1 (valentyusb.usbcore.sm.send_test.TestTxPacketSendAutoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 133, in test_status1
    self.sim(PID.DATA1, [])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 207, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendAutoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_ack (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 121, in test_ack
    self.sim(PID.ACK)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 185, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendNoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_data0_all_zero (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 154, in test_data0_all_zero
    self.sim(PID.DATA0, data=[0, 0, 0, 0])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 185, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendNoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_data0_dat1234 (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 157, in test_data0_dat1234
    self.sim(PID.DATA0, data=[1, 2, 3, 4])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 185, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendNoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_data0_descriptor (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 164, in test_data0_descriptor
    0x80, 0x06, 0x00, 0x01, 0x00, 0x00, 0x40, 0x00, 0xdd, 0x94,
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 185, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendNoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_data0_edges (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 151, in test_data0_edges
    self.sim(PID.DATA0, data=[0b00000001, 0, 0, 0b10000000])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 185, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendNoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_data0_one_one (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 142, in test_data0_one_one
    self.sim(PID.DATA0, [0b10000001])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 185, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendNoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_data0_one_zero (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 136, in test_data0_one_zero
    self.sim(PID.DATA0, [0])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 185, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendNoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_data0_two_ones (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 148, in test_data0_two_ones
    self.sim(PID.DATA0, [0, 1])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 185, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendNoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_data1_all_zero (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 160, in test_data1_all_zero
    self.sim(PID.DATA1, data=[0, 0, 0, 0])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 185, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendNoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_nak (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 124, in test_nak
    self.sim(PID.NAK)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 185, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendNoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_stall (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 127, in test_stall
    self.sim(PID.STALL)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 185, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendNoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_status0 (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 130, in test_status0
    self.sim(PID.DATA0, [])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 185, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendNoCrc' object has no attribute 'make_vcd_name'

======================================================================
ERROR: test_status1 (valentyusb.usbcore.sm.send_test.TestTxPacketSendNoCrc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 133, in test_status1
    self.sim(PID.DATA1, [])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/send_test.py", line 185, in sim
    vcd_name=self.make_vcd_name(),
AttributeError: 'TestTxPacketSendNoCrc' object has no attribute 'make_vcd_name'

----------------------------------------------------------------------
Ran 26 tests in 0.172s

FAILED (errors=26)
python3 ../../lxbuildenv.py -r -m unittest -v valentyusb.usbcore.sm.transfer_test
test_control_setup (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... ok
test_control_setup_clears_stall (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... FAIL
test_control_transfer_in (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... FAIL
test_control_transfer_in_nak_data (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... ok
test_control_transfer_in_nak_status (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... FAIL
test_control_transfer_out (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... FAIL
test_control_transfer_out_nak_data (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... FAIL
test_control_transfer_out_nak_status (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... FAIL
test_data_in_byte_1 (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... ok
test_data_in_byte_2 (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... ok
test_data_in_byte_a (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... ok
test_data_toggle_bit_multiple_endpoints (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... ok
test_in_stall (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... ok
test_in_transfer (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... ok
test_in_transfer_nak (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... ok
test_out_stall (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... FAIL
test_out_transfer (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... FAIL
test_out_transfer_nak (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... FAIL
test_setup_clears_data_toggle_bit (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... FAIL
test_sof_is_ignored (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... FAIL
test_sof_stuffing (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer) ... ok

======================================================================
FAIL: test_control_setup_clears_stall (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 615, in test_control_setup_clears_stall
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 106, in run_sim
    clocks={"sys": 12, "usb_48": 48, "usb_12": 192},
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 98, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 594, in stim
    yield from self.expect_data(epaddr_out, d[:4])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 293, in expect_data
    self.assertTrue(pending)
AssertionError: False is not true

======================================================================
FAIL: test_control_transfer_in (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 631, in test_control_transfer_in
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 106, in run_sim
    clocks={"sys": 12, "usb_48": 48, "usb_12": 192},
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 98, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 629, in stim
    0x08, 0x09, 0x0A, 0x0B],
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 408, in control_transfer_in
    yield from self.transaction_setup(addr, setup_data)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 290, in transaction_setup
    yield from self.expect_data(epaddr_out, data)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 293, in expect_data
    self.assertTrue(pending)
AssertionError: False is not true

======================================================================
FAIL: test_control_transfer_in_nak_status (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 698, in test_control_transfer_in_nak_status
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 106, in run_sim
    clocks={"sys": 12, "usb_48": 48, "usb_12": 192},
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 98, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 675, in stim
    yield from self.transaction_setup(addr, setup_data)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 290, in transaction_setup
    yield from self.expect_data(epaddr_out, data)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 293, in expect_data
    self.assertTrue(pending)
AssertionError: False is not true

======================================================================
FAIL: test_control_transfer_out (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 714, in test_control_transfer_out
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 106, in run_sim
    clocks={"sys": 12, "usb_48": 48, "usb_12": 192},
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 98, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 712, in stim
    0x08, 0x09, 0x0A, 0x0B],
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 431, in control_transfer_out
    yield from self.transaction_setup(addr, setup_data)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 290, in transaction_setup
    yield from self.expect_data(epaddr_out, data)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 293, in expect_data
    self.assertTrue(pending)
AssertionError: False is not true

======================================================================
FAIL: test_control_transfer_out_nak_data (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 754, in test_control_transfer_out_nak_data
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 106, in run_sim
    clocks={"sys": 12, "usb_48": 48, "usb_12": 192},
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 98, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 730, in stim
    yield from self.transaction_setup(addr, setup_data)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 290, in transaction_setup
    yield from self.expect_data(epaddr_out, data)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 293, in expect_data
    self.assertTrue(pending)
AssertionError: False is not true

======================================================================
FAIL: test_control_transfer_out_nak_status (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 798, in test_control_transfer_out_nak_status
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 106, in run_sim
    clocks={"sys": 12, "usb_48": 48, "usb_12": 192},
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 98, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 773, in stim
    yield from self.transaction_setup(addr, setup_data)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 290, in transaction_setup
    yield from self.expect_data(epaddr_out, data)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 293, in expect_data
    self.assertTrue(pending)
AssertionError: False is not true

======================================================================
FAIL: test_out_stall (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 1195, in test_out_stall
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 106, in run_sim
    clocks={"sys": 12, "usb_48": 48, "usb_12": 192},
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 98, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 1177, in stim
    yield from self.expect_data(epaddr, d[:4])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 293, in expect_data
    self.assertTrue(pending)
AssertionError: False is not true

======================================================================
FAIL: test_out_transfer (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 1117, in test_out_transfer
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 106, in run_sim
    clocks={"sys": 12, "usb_48": 48, "usb_12": 192},
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 98, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 1094, in stim
    yield from self.expect_data(epaddr, d)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 293, in expect_data
    self.assertTrue(pending)
AssertionError: False is not true

======================================================================
FAIL: test_out_transfer_nak (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 1152, in test_out_transfer_nak
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 106, in run_sim
    clocks={"sys": 12, "usb_48": 48, "usb_12": 192},
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 98, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 1149, in stim
    yield from self.expect_data(epaddr, d)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 293, in expect_data
    self.assertTrue(pending)
AssertionError: False is not true

======================================================================
FAIL: test_setup_clears_data_toggle_bit (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 952, in test_setup_clears_data_toggle_bit
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 106, in run_sim
    clocks={"sys": 12, "usb_48": 48, "usb_12": 192},
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 98, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 895, in stim
    yield from self.transaction_setup(28, [0x80, 0x06, 0x00, 0x06, 0x00, 0x00, 0x0A, 0x00])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 290, in transaction_setup
    yield from self.expect_data(epaddr_out, data)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 293, in expect_data
    self.assertTrue(pending)
AssertionError: False is not true

======================================================================
FAIL: test_sof_is_ignored (valentyusb.usbcore.sm.transfer_test.TestUsbTransfer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 571, in test_sof_is_ignored
    self.run_sim(stim)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 106, in run_sim
    clocks={"sys": 12, "usb_48": 48, "usb_12": 192},
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 98, in padfront
    yield from stim()
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/test/common.py", line 524, in stim
    yield from self.expect_data(epaddr_out, data)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/sm/transfer_test.py", line 293, in expect_data
    self.assertTrue(pending)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 21 tests in 249.098s

FAILED (failures=11)
./run_tests.sh: line 7: ----------: command not found
python3 ../../lxbuildenv.py -r -m unittest -v valentyusb.usbcore.tx.bitstuff_test
test_bitstuff (valentyusb.usbcore.tx.bitstuff_test.TestTxBitstuffer) ... ok
test_bitstuff_at_eop (valentyusb.usbcore.tx.bitstuff_test.TestTxBitstuffer) ... ok
test_bitstuff_input_stall (valentyusb.usbcore.tx.bitstuff_test.TestTxBitstuffer) ... ok
test_bitstuff_se0 (valentyusb.usbcore.tx.bitstuff_test.TestTxBitstuffer) ... ok
test_multi_bitstuff (valentyusb.usbcore.tx.bitstuff_test.TestTxBitstuffer) ... ok
test_passthrough (valentyusb.usbcore.tx.bitstuff_test.TestTxBitstuffer) ... ok
test_passthrough_se0 (valentyusb.usbcore.tx.bitstuff_test.TestTxBitstuffer) ... ok

----------------------------------------------------------------------
Ran 7 tests in 0.052s

OK
python3 ../../lxbuildenv.py -r -m unittest -v valentyusb.usbcore.tx.crc_test
test_00000000_byte (valentyusb.usbcore.tx.crc_test.TestCrcPipeline) ... FAIL
test_00000001_byte (valentyusb.usbcore.tx.crc_test.TestCrcPipeline) ... FAIL
test_10000000_byte (valentyusb.usbcore.tx.crc_test.TestCrcPipeline) ... FAIL
test_10101010_byte (valentyusb.usbcore.tx.crc_test.TestCrcPipeline) ... FAIL
test_11111111_byte (valentyusb.usbcore.tx.crc_test.TestCrcPipeline) ... ok
test_sequential_bytes (valentyusb.usbcore.tx.crc_test.TestCrcPipeline) ... FAIL
test_sequential_bytes2 (valentyusb.usbcore.tx.crc_test.TestCrcPipeline) ... FAIL
test_sequential_bytes3 (valentyusb.usbcore.tx.crc_test.TestCrcPipeline) ... FAIL
test_zero_bytes (valentyusb.usbcore.tx.crc_test.TestCrcPipeline) ... FAIL
test_data_crc16_nonzero1 (valentyusb.usbcore.tx.crc_test.TestTxParallelCrcGenerator) ... ok
test_data_crc16_nonzero2 (valentyusb.usbcore.tx.crc_test.TestTxParallelCrcGenerator) ... ok
test_token_crc5_nonzero1 (valentyusb.usbcore.tx.crc_test.TestTxParallelCrcGenerator) ... ok
test_token_crc5_zeroes (valentyusb.usbcore.tx.crc_test.TestTxParallelCrcGenerator) ... ok
test_data_crc16_nonzero (valentyusb.usbcore.tx.crc_test.TestTxSerialCrcGenerator) ... ERROR
test_token_crc5_nonzero (valentyusb.usbcore.tx.crc_test.TestTxSerialCrcGenerator) ... FAIL
test_token_crc5_nonzero_stall (valentyusb.usbcore.tx.crc_test.TestTxSerialCrcGenerator) ... FAIL
test_token_crc5_zeroes (valentyusb.usbcore.tx.crc_test.TestTxSerialCrcGenerator) ... FAIL
test_token_crc5_zeroes_alt (valentyusb.usbcore.tx.crc_test.TestTxSerialCrcGenerator) ... FAIL

======================================================================
ERROR: test_data_crc16_nonzero (valentyusb.usbcore.tx.crc_test.TestTxSerialCrcGenerator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 92, in test_data_crc16_nonzero
    o_crc      =("                                                                        *", [0x94dd])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/tester.py", line 136, in run
    run_simulation(dut, stim(), vcd_name=self.vcd_name)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/tester.py", line 100, in stim
    if test_args[list(self.outputs.keys())[0]][j] != '|':
IndexError: tuple index out of range

======================================================================
FAIL: test_00000000_byte (valentyusb.usbcore.tx.crc_test.TestCrcPipeline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 202, in test_00000000_byte
    self.sim([0])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 193, in sim
    run_simulation(dut, stim(), vcd_name=self.make_vcd_name())
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 183, in stim
    self.assertSequenceEqual(encoded_expected_crc, encoded_actual_crc)
AssertionError: Sequences differ: '0000001011111101' != '1000001011111000'

First differing element 0:
'0'
'1'

- '0000001011111101'
?  ^            - ^

+ '1000001011111000'
?  ^             ^^


======================================================================
FAIL: test_00000001_byte (valentyusb.usbcore.tx.crc_test.TestCrcPipeline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 196, in test_00000001_byte
    self.sim([0b00000001])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 193, in sim
    run_simulation(dut, stim(), vcd_name=self.make_vcd_name())
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 183, in stim
    self.assertSequenceEqual(encoded_expected_crc, encoded_actual_crc)
AssertionError: Sequences differ: '1000000111111110' != '1000001011111000'

First differing element 6:
'0'
'1'

- '1000000111111110'
?              ^^^

+ '1000001011111000'
?        +      ^^


======================================================================
FAIL: test_10000000_byte (valentyusb.usbcore.tx.crc_test.TestCrcPipeline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 199, in test_10000000_byte
    self.sim([0b10000000])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 193, in sim
    run_simulation(dut, stim(), vcd_name=self.make_vcd_name())
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 183, in stim
    self.assertSequenceEqual(encoded_expected_crc, encoded_actual_crc)
AssertionError: Sequences differ: '1000001011111000' != '0000001011110111'

First differing element 0:
'1'
'0'

- '1000001011111000'
?  ^            ^^^

+ '0000001011110111'
?  ^           + ^^


======================================================================
FAIL: test_10101010_byte (valentyusb.usbcore.tx.crc_test.TestCrcPipeline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 208, in test_10101010_byte
    self.sim([0b10101010])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 193, in sim
    run_simulation(dut, stim(), vcd_name=self.make_vcd_name())
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 183, in stim
    self.assertSequenceEqual(encoded_expected_crc, encoded_actual_crc)
AssertionError: Sequences differ: '0000001100000011' != '1000000100000100'

First differing element 0:
'0'
'1'

- '0000001100000011'
+ '1000000100000100'

======================================================================
FAIL: test_sequential_bytes (valentyusb.usbcore.tx.crc_test.TestCrcPipeline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 214, in test_sequential_bytes
    self.sim([0, 1, 2])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 193, in sim
    run_simulation(dut, stim(), vcd_name=self.make_vcd_name())
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 183, in stim
    self.assertSequenceEqual(encoded_expected_crc, encoded_actual_crc)
AssertionError: Sequences differ: '0111000001110110' != '1111001011101101'

First differing element 0:
'0'
'1'

- '0111000001110110'
?  ^     ^^

+ '1111001011101101'
?  ^     ^        +


======================================================================
FAIL: test_sequential_bytes2 (valentyusb.usbcore.tx.crc_test.TestCrcPipeline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 217, in test_sequential_bytes2
    self.sim([0, 1])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 193, in sim
    run_simulation(dut, stim(), vcd_name=self.make_vcd_name())
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 183, in stim
    self.assertSequenceEqual(encoded_expected_crc, encoded_actual_crc)
AssertionError: Sequences differ: '1111110011110001' != '0111100111110100'

First differing element 0:
'1'
'0'

- '1111110011110001'
?  ^^            --

+ '0111100111110100'
?  ^          +++


======================================================================
FAIL: test_sequential_bytes3 (valentyusb.usbcore.tx.crc_test.TestCrcPipeline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 220, in test_sequential_bytes3
    self.sim([1, 0])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 193, in sim
    run_simulation(dut, stim(), vcd_name=self.make_vcd_name())
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 183, in stim
    self.assertSequenceEqual(encoded_expected_crc, encoded_actual_crc)
AssertionError: Sequences differ: '1111111111111011' != '1111111111110111'

First differing element 12:
'1'
'0'

- '1111111111111011'
?  -

+ '1111111111110111'
?                 +


======================================================================
FAIL: test_zero_bytes (valentyusb.usbcore.tx.crc_test.TestCrcPipeline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 211, in test_zero_bytes
    self.sim([0, 0, 0])
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 193, in sim
    run_simulation(dut, stim(), vcd_name=self.make_vcd_name())
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 183, in stim
    self.assertSequenceEqual(encoded_expected_crc, encoded_actual_crc)
AssertionError: Sequences differ: '0111000111111100' != '1111000111111001'

First differing element 0:
'0'
'1'

- '0111000111111100'
?  ^            -

+ '1111000111111001'
?  ^              +


======================================================================
FAIL: test_token_crc5_nonzero (valentyusb.usbcore.tx.crc_test.TestTxSerialCrcGenerator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 68, in test_token_crc5_nonzero
    o_crc      = "            ccc"
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/tester.py", line 136, in run
    run_simulation(dut, stim(), vcd_name=self.vcd_name)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/tester.py", line 110, in stim
    assert len(actual_output[output_signal]) == j
AssertionError

======================================================================
FAIL: test_token_crc5_nonzero_stall (valentyusb.usbcore.tx.crc_test.TestTxSerialCrcGenerator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 80, in test_token_crc5_nonzero_stall
    o_crc      = "                           ccc"
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/tester.py", line 136, in run
    run_simulation(dut, stim(), vcd_name=self.vcd_name)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/tester.py", line 110, in stim
    assert len(actual_output[output_signal]) == j
AssertionError

======================================================================
FAIL: test_token_crc5_zeroes (valentyusb.usbcore.tx.crc_test.TestTxSerialCrcGenerator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 44, in test_token_crc5_zeroes
    o_crc      = "             222"
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/tester.py", line 136, in run
    run_simulation(dut, stim(), vcd_name=self.vcd_name)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/tester.py", line 110, in stim
    assert len(actual_output[output_signal]) == j
AssertionError

======================================================================
FAIL: test_token_crc5_zeroes_alt (valentyusb.usbcore.tx.crc_test.TestTxSerialCrcGenerator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/crc_test.py", line 56, in test_token_crc5_zeroes_alt
    o_crc      = "            222"
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/tester.py", line 136, in run
    run_simulation(dut, stim(), vcd_name=self.vcd_name)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/tester.py", line 110, in stim
    assert len(actual_output[output_signal]) == j
AssertionError

----------------------------------------------------------------------
Ran 18 tests in 0.338s

FAILED (failures=12, errors=1)
./run_tests.sh: line 7: crc16: command not found
python3 ../../lxbuildenv.py -r -m unittest -v valentyusb.usbcore.tx.nrzi_test
test_setup_token (valentyusb.usbcore.tx.nrzi_test.TestTxNRZIEncoder) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.020s

OK
python3 ../../lxbuildenv.py -r -m unittest -v valentyusb.usbcore.tx.pipeline_test
test_usb2_ack_handshake (valentyusb.usbcore.tx.pipeline_test.TestTxPipeline) ... test_usb2_ack_handshake_pid_error (valentyusb.usbcore.tx.pipeline_test.TestTxPipeline) ... test_usb2_data_with_bad_crc16 (valentyusb.usbcore.tx.pipeline_test.TestTxPipeline) ... test_usb2_data_with_good_crc16 (valentyusb.usbcore.tx.pipeline_test.TestTxPipeline) ... test_usb2_sof_token (valentyusb.usbcore.tx.pipeline_test.TestTxPipeline) ... test_usb2_sof_token_bad_crc5 (valentyusb.usbcore.tx.pipeline_test.TestTxPipeline) ... test_usb2_sof_token_bad_pid (valentyusb.usbcore.tx.pipeline_test.TestTxPipeline) ... 
======================================================================
FAIL: test_usb2_ack_handshake (valentyusb.usbcore.tx.pipeline_test.TestTxPipeline) (name='USB2 ACK handshake')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/pipeline_test.py", line 88, in pkt_decode_test
    clocks={"sys": 10, "usb_48": 40, "usb_12": 160})
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/pipeline_test.py", line 80, in stim
    self.assertSequenceEqual(expected_usbp, actual_usbp[PAD:len(expected_usbp)+PAD])
AssertionError: Sequences differ: '111111110000111100001111000011110000000011111[47 chars]1111' != '111100001111000011110000111100000000111100001[47 chars]1111'

First differing element 4:
'1'
'0'

- '111111110000111100001111000011110000000011111111000011111111000000000000000000001111111111111111'
?  ----                                                                ^^^^^^^^^^^^

+ '111100001111000011110000111100000000111100001111000011110000111111110000000011111111111111111111'
?                                          ++++++++++++                        ^^^^


======================================================================
FAIL: test_usb2_ack_handshake_pid_error (valentyusb.usbcore.tx.pipeline_test.TestTxPipeline) (name='USB2 ACK handshake - pid error')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/pipeline_test.py", line 88, in pkt_decode_test
    clocks={"sys": 10, "usb_48": 40, "usb_12": 160})
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/pipeline_test.py", line 80, in stim
    self.assertSequenceEqual(expected_usbp, actual_usbp[PAD:len(expected_usbp)+PAD])
AssertionError: Sequences differ: '111111110000111100001111000011110000000011111[47 chars]1111' != '111100001111000011110000111100000000111100001[47 chars]1111'

First differing element 4:
'1'
'0'

- '111111110000111100001111000011110000000011111111000011111111111111111111000000001111111111111111'
?  ----                                                    ^^^^^^^^

+ '111100001111000011110000111100000000111100001111000011110000111111110000000011111111111111111111'
?                                          ++++            ^^^^                                ++++


======================================================================
FAIL: test_usb2_data_with_bad_crc16 (valentyusb.usbcore.tx.pipeline_test.TestTxPipeline) (name='USB2 data with bad CRC16')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/pipeline_test.py", line 88, in pkt_decode_test
    clocks={"sys": 10, "usb_48": 40, "usb_12": 160})
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/pipeline_test.py", line 80, in stim
    self.assertSequenceEqual(expected_usbp, actual_usbp[PAD:len(expected_usbp)+PAD])
AssertionError: Sequences differ: '111111110000111100001111000011110000000000000[367 chars]1111' != '111100001111000011110000111100000000111100001[367 chars]1111'

First differing element 4:
'1'
'0'

- '11111111000011110000111100001111000000000000000011110000111100000000000011110000111100001111000011111111000000000000111100001111000011110000111100001111000011110000111111110000111100001111000011110000111100001111000011110000111100001111000011110000111100001111000011110000111100001111000000001111000011110000111100001111000011111111000000000000000011111111111100001111111100000000111111111111000000001111111111111111'
+ '11110000111100001111000011110000000011110000111100001111000011111111111111110000111100001111111111110000111100001111000011110000000011111111111100001111000011110000111100001111000011110000111100000000111100001111000011110000111100001111000011110000111100001111000011110000111100001111000011110000111100001111000011111111000011110000111100001111000011110000000011111111111111110000000000000000000011111111111111111111'

======================================================================
FAIL: test_usb2_data_with_good_crc16 (valentyusb.usbcore.tx.pipeline_test.TestTxPipeline) (name='USB2 data with good CRC16')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/pipeline_test.py", line 88, in pkt_decode_test
    clocks={"sys": 10, "usb_48": 40, "usb_12": 160})
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/pipeline_test.py", line 80, in stim
    self.assertSequenceEqual(expected_usbp, actual_usbp[PAD:len(expected_usbp)+PAD])
AssertionError: Sequences differ: '111111110000111100001111000011110000000000000[367 chars]1111' != '111100001111000011110000111100000000111100001[367 chars]1111'

First differing element 4:
'1'
'0'

- '11111111000011110000111100001111000000000000000011110000111100000000000011110000111100001111000011111111000000000000111100001111000011110000111100001111000011110000111111110000111100001111000011110000111100001111000011110000111100001111000011110000111100001111000011110000111100001111000000001111000011110000111100001111000011111111000000000000000011111111111100001111111100000000111100000000000000001111111111111111'
+ '11110000111100001111000011110000000011110000111100001111000011111111111111110000111100001111111111110000111100001111000011110000000011111111111100001111000011110000111100001111000011110000111100000000111100001111000011110000111100001111000011110000111100001111000011110000111100001111000011110000111100001111000011111111000011110000111100001111000011110000000011111111111111110000000000000000000011111111111111111111'

======================================================================
FAIL: test_usb2_sof_token (valentyusb.usbcore.tx.pipeline_test.TestTxPipeline) (name='USB2 SOF token')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/pipeline_test.py", line 88, in pkt_decode_test
    clocks={"sys": 10, "usb_48": 40, "usb_12": 160})
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/pipeline_test.py", line 80, in stim
    self.assertSequenceEqual(expected_usbp, actual_usbp[PAD:len(expected_usbp)+PAD])
AssertionError: Sequences differ: '111111110000111100001111000011110000000000001[111 chars]1111' != '111100001111000011110000111100000000000011110[111 chars]1111'

First differing element 4:
'1'
'0'

- '1111111100001111000011110000111100000000000011111111000011111111000000000000111100001111000000000000111111111111000011110000111111110000000000001111111111111111'
?                                                                                                          --------------------------------

+ '1111000011110000111100001111000000000000111100001111000011110000000000001111111100001111111100000000000011110000111100000000000011110000000011111111111111111111'
?      ++++    ++++++++++++++++++++++++                                                                                                                        ++++


======================================================================
FAIL: test_usb2_sof_token_bad_crc5 (valentyusb.usbcore.tx.pipeline_test.TestTxPipeline) (name='USB2 SOF token - bad crc5')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/pipeline_test.py", line 88, in pkt_decode_test
    clocks={"sys": 10, "usb_48": 40, "usb_12": 160})
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/pipeline_test.py", line 80, in stim
    self.assertSequenceEqual(expected_usbp, actual_usbp[PAD:len(expected_usbp)+PAD])
AssertionError: Sequences differ: '111111110000111100001111000011110000000000001[111 chars]1111' != '111100001111000011110000111100000000111100001[111 chars]1111'

First differing element 4:
'1'
'0'

- '1111111100001111000011110000111100000000000011111111000011111111000000000000111100001111000000000000111111111111000011110000111111111111000000001111111111111111'
?  ----                                    ----    ------------------------

+ '1111000011110000111100001111000000001111000011110000111100001111111111110000000011110000000011111111111100001111000011111111111100000000000011111111111111111111'
?                                                              ++++++++++++++++++++++++                                                    ++++++++


======================================================================
FAIL: test_usb2_sof_token_bad_pid (valentyusb.usbcore.tx.pipeline_test.TestTxPipeline) (name='USB2 SOF token - bad pid')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/pipeline_test.py", line 88, in pkt_decode_test
    clocks={"sys": 10, "usb_48": 40, "usb_12": 160})
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/pipeline_test.py", line 80, in stim
    self.assertSequenceEqual(expected_usbp, actual_usbp[PAD:len(expected_usbp)+PAD])
AssertionError: Sequences differ: '111111110000111100001111000011110000000000001[111 chars]1111' != '111100001111000011110000111100000000111100001[111 chars]1111'

First differing element 4:
'1'
'0'

- '1111111100001111000011110000111100000000000011111111000011111111000011111111000011110000111111111111000000000000111100001111000000001111000000001111111111111111'
?  ----                                    --------        ----------------

+ '1111000011110000111100001111000000001111000011110000111100001111111111110000000011110000000011110000000011110000111100000000000011110000000011111111111111111111'
?                                                                                  ++++++++++++++++++++                ++++                                    ++++


----------------------------------------------------------------------
Ran 7 tests in 2.993s

FAILED (failures=7)
python3 ../../lxbuildenv.py -r -m unittest -v valentyusb.usbcore.tx.shifter_test
test_basic_shift_out_1 (valentyusb.usbcore.tx.shifter_test.TestTxShifter) ... test_basic_shift_out_2 (valentyusb.usbcore.tx.shifter_test.TestTxShifter) ... test_basic_shift_out_3 (valentyusb.usbcore.tx.shifter_test.TestTxShifter) ... test_multistall_shift_out_1 (valentyusb.usbcore.tx.shifter_test.TestTxShifter) ... test_multistall_shift_out_2 (valentyusb.usbcore.tx.shifter_test.TestTxShifter) ... test_multistall_shift_out_3 (valentyusb.usbcore.tx.shifter_test.TestTxShifter) ... test_stall_shift_out_1 (valentyusb.usbcore.tx.shifter_test.TestTxShifter) ... test_stall_shift_out_2 (valentyusb.usbcore.tx.shifter_test.TestTxShifter) ... test_stall_shift_out_3 (valentyusb.usbcore.tx.shifter_test.TestTxShifter) ... 
======================================================================
FAIL: test_basic_shift_out_1 (valentyusb.usbcore.tx.shifter_test.TestTxShifter) (name='basic shift out 1', vector={'width': 8, 'data': [], 'reset': '-|________|________|________', 'ce': '-|--------|--------|--------', 'out': '0|00000001|00000001|00000001', 'get': '-|_______-|_______-|_______-'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/shifter_test.py", line 63, in shifter_test
    vcd_name=self.make_vcd_name(testsuffix=fname))
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/shifter_test.py", line 56, in stim
    self.assertSequenceEqual(get, actual_get)
AssertionError: Sequences differ: '-|_______-|_______-|_______-' != '_|-_______|-_______|-_______'

First differing element 0:
'-'
'_'

- '-|_______-|_______-|_______-'
?   -        -        -       -

+ '_|-_______|-_______|-_______'
?  ++        +        +


======================================================================
FAIL: test_basic_shift_out_2 (valentyusb.usbcore.tx.shifter_test.TestTxShifter) (name='basic shift out 2', vector={'width': 8, 'data': [], 'reset': '-|________|________|________', 'ce': '-|--------|--------|--------', 'out': '0|10000000|10000000|10000000', 'get': '-|_______-|_______-|_______-'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/shifter_test.py", line 63, in shifter_test
    vcd_name=self.make_vcd_name(testsuffix=fname))
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/shifter_test.py", line 56, in stim
    self.assertSequenceEqual(get, actual_get)
AssertionError: Sequences differ: '-|_______-|_______-|_______-' != '_|-_______|-_______|-_______'

First differing element 0:
'-'
'_'

- '-|_______-|_______-|_______-'
?   -        -        -       -

+ '_|-_______|-_______|-_______'
?  ++        +        +


======================================================================
FAIL: test_basic_shift_out_3 (valentyusb.usbcore.tx.shifter_test.TestTxShifter) (name='basic shift out 3', vector={'width': 8, 'data': [], 'reset': '-|________|________|________', 'ce': '-|--------|--------|--------', 'out': '0|01100110|10000001|10000000', 'get': '-|_______-|_______-|_______-'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/shifter_test.py", line 63, in shifter_test
    vcd_name=self.make_vcd_name(testsuffix=fname))
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/shifter_test.py", line 56, in stim
    self.assertSequenceEqual(get, actual_get)
AssertionError: Sequences differ: '-|_______-|_______-|_______-' != '_|-_______|-_______|-_______'

First differing element 0:
'-'
'_'

- '-|_______-|_______-|_______-'
?   -        -        -       -

+ '_|-_______|-_______|-_______'
?  ++        +        +


======================================================================
FAIL: test_multistall_shift_out_1 (valentyusb.usbcore.tx.shifter_test.TestTxShifter) (name='mutlistall shift out 1', vector={'width': 8, 'data': [], 'reset': '-|___________|_________|_________', 'ce': '-|--___------|--------_|----_----', 'out': '0|00000000001|000000011|000000001', 'get': '-|__________-|_______--|________-'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/shifter_test.py", line 63, in shifter_test
    vcd_name=self.make_vcd_name(testsuffix=fname))
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/shifter_test.py", line 56, in stim
    self.assertSequenceEqual(get, actual_get)
AssertionError: Sequences differ: '-|__________-|_______--|________-' != '_|-__________|-________|-________'

First differing element 0:
'-'
'_'

- '-|__________-|_______--|________-'
+ '_|-__________|-________|-________'

======================================================================
FAIL: test_multistall_shift_out_2 (valentyusb.usbcore.tx.shifter_test.TestTxShifter) (name='mutlistall shift out 2', vector={'width': 8, 'data': [], 'reset': '-|____________|________|__________', 'ce': '-|---____-----|--------|-_----_---', 'out': '0|100000000000|10000000|1100000000', 'get': '-|___________-|_______-|_________-'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/shifter_test.py", line 63, in shifter_test
    vcd_name=self.make_vcd_name(testsuffix=fname))
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/shifter_test.py", line 56, in stim
    self.assertSequenceEqual(get, actual_get)
AssertionError: Sequences differ: '-|___________-|_______-|_________-' != '_|-___________|-_______|--________'

First differing element 0:
'-'
'_'

- '-|___________-|_______-|_________-'
?   -            -        ^        --

+ '_|-___________|-_______|--________'
?  ++            +        + ^


======================================================================
FAIL: test_multistall_shift_out_3 (valentyusb.usbcore.tx.shifter_test.TestTxShifter) (name='mutlistall shift out 3', vector={'width': 8, 'data': [], 'reset': '-|____________|___________|_________', 'ce': '-|---____-----|--------___|-_-------', 'out': '0|011111100110|10000001111|110000000', 'get': '-|___________-|_______----|________-'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/shifter_test.py", line 63, in shifter_test
    vcd_name=self.make_vcd_name(testsuffix=fname))
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/shifter_test.py", line 56, in stim
    self.assertSequenceEqual(get, actual_get)
AssertionError: Sequences differ: '-|___________-|_______----|________-' != '_|-___________|-__________|--_______'

First differing element 0:
'-'
'_'

- '-|___________-|_______----|________-'
+ '_|-___________|-__________|--_______'

======================================================================
FAIL: test_stall_shift_out_1 (valentyusb.usbcore.tx.shifter_test.TestTxShifter) (name='stall shift out 1', vector={'width': 8, 'data': [], 'reset': '-|_________|________|________', 'ce': '-|--_------|--------|--------', 'out': '0|000000001|00000001|00000001', 'get': '-|________-|_______-|_______-'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/shifter_test.py", line 63, in shifter_test
    vcd_name=self.make_vcd_name(testsuffix=fname))
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/shifter_test.py", line 56, in stim
    self.assertSequenceEqual(get, actual_get)
AssertionError: Sequences differ: '-|________-|_______-|_______-' != '_|-________|-_______|-_______'

First differing element 0:
'-'
'_'

- '-|________-|_______-|_______-'
?   -         -        -       -

+ '_|-________|-_______|-_______'
?  ++         +        +


======================================================================
FAIL: test_stall_shift_out_2 (valentyusb.usbcore.tx.shifter_test.TestTxShifter) (name='stall shift out 2', vector={'width': 8, 'data': [], 'reset': '-|_________|________|________', 'ce': '-|---_-----|--------|--------', 'out': '0|100000000|10000000|10000000', 'get': '-|________-|_______-|_______-'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/shifter_test.py", line 63, in shifter_test
    vcd_name=self.make_vcd_name(testsuffix=fname))
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/shifter_test.py", line 56, in stim
    self.assertSequenceEqual(get, actual_get)
AssertionError: Sequences differ: '-|________-|_______-|_______-' != '_|-________|-_______|-_______'

First differing element 0:
'-'
'_'

- '-|________-|_______-|_______-'
?   -         -        -       -

+ '_|-________|-_______|-_______'
?  ++         +        +


======================================================================
FAIL: test_stall_shift_out_3 (valentyusb.usbcore.tx.shifter_test.TestTxShifter) (name='stall shift out 3', vector={'width': 8, 'data': [], 'reset': '-|_________|________|________', 'ce': '-|---_-----|--------|--------', 'out': '0|011100110|10000001|10000000', 'get': '-|________-|_______-|_______-'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/shifter_test.py", line 63, in shifter_test
    vcd_name=self.make_vcd_name(testsuffix=fname))
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 414, in run_simulation
    s.run()
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 403, in run
    self._process_generators(cd)
  File "/opt/usbalex/foboot/hw/deps/migen/migen/sim/core.py", line 357, in _process_generators
    request = generator.send(reply)
  File "/opt/usbalex/foboot/hw/deps/valentyusb/valentyusb/usbcore/tx/shifter_test.py", line 56, in stim
    self.assertSequenceEqual(get, actual_get)
AssertionError: Sequences differ: '-|________-|_______-|_______-' != '_|-________|-_______|-_______'

First differing element 0:
'-'
'_'

- '-|________-|_______-|_______-'
?   -         -        -       -

+ '_|-________|-_______|-_______'
?  ++         +        +


----------------------------------------------------------------------
Ran 9 tests in 0.063s

FAILED (failures=9)
